# Generated by Django 5.2.17 on 2026-10-01 14:35

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="membership",
            options={"default_manager_name": "unscoped_objects"},
        ),
        migrations.AlterModelManagers(
            name="membership",
            managers=[
                ("unscoped_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
