# Generated by Django 5.2.17 on 2026-10-02 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_membership_options_alter_membership_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="google_subject",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
