# Generated by Django 5.2.17 on 2026-10-02 11:20

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0003_user_google_subject"),
    ]

    operations = [
        migrations.CreateModel(
            name="GmailConnection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("provider_account_id", models.CharField(max_length=255)),
                ("email_address", models.EmailField(max_length=254)),
                ("scopes", models.JSONField(default=list)),
                ("encrypted_credentials", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("connected", "Connected"),
                            ("disconnected", "Disconnected"),
                            ("revoked", "Access revoked"),
                            ("expired", "Credentials expired"),
                            ("error", "Needs attention"),
                        ],
                        max_length=20,
                    ),
                ),
                ("consented_at", models.DateTimeField()),
                ("connected_at", models.DateTimeField()),
                ("disconnected_at", models.DateTimeField(blank=True, null=True)),
                ("token_refreshed_at", models.DateTimeField(blank=True, null=True)),
                ("last_checked_at", models.DateTimeField(blank=True, null=True)),
                ("last_error_code", models.CharField(blank=True, max_length=50)),
                ("history_id", models.CharField(blank=True, max_length=255)),
                ("sync_page_token", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "workspace",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gmail_connection",
                        to="accounts.workspace",
                    ),
                ),
            ],
            options={
                "default_manager_name": "unscoped_objects",
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "connected")),
                        fields=("provider_account_id",),
                        name="unique_active_gmail_provider_account",
                    )
                ],
            },
            managers=[
                ("unscoped_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
